services:
  web:
    image: nginx:latest # Or any other simple image
    ports:
      - "80:80"
    restart: always
  web2:
    image: nginx:latest
    ports:
      - "81:80"
    restart: always
  web3:
    image: nginx:latest
    ports:
      -  "85:80"
    restart: always
