name: stacktest
services:
  web:
    image: nginx:latest # Or any other simple image
    ports:
      - "80:80"
    restart: always
  web2:
    image: nginx:latest
    ports:
      - "81:80"
    restart: always
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped