[[server]] # Declare a new server
name = "server-test"
description = "the prod server"
tags = ["prod"]
[server.config]
address = "https://192.168.1.25:8120"
region = "paco"
enabled = true # default: false
