[[stack]]
name = "stack"
[stack.config]
server = "server-test"
destroy_before_deploy = true
pre_deploy.command = """
  docker volume create uptimekuma
"""
file_contents = """
--
name: home
services:
  uptime-kuma:
    container_name: uptime-kumas
    image: louislam/uptime-kuma
    restart: always
    ports:
      - 3001:3001
    volumes:
      - uptimekuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
  

volumes:
  uptimekuma:
    external: true
"""
