[[stack]]
name = "stack"
[stack.config]
server = "server-test"
destroy_before_deploy = true
"""
file_contents = """
--
name: home
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    restart: unless-stopped
"""
